@host = http://localhost:8000

###
GET {{host}}

###
GET {{host}}/blog 

###
GET {{host}}/blog/Mike

###
POST {{host}}/blog 
Content-Type: application/json

{
    "author": "Mike",
    "email": "mike@gmail.com",
    "topic": "sports",
    "text" : "I am playing football",
    "rating": 3
}

###
PATCH {{host}}/blog/6458175d73621e96887a7d34
Content-Type: application/json

{
    "rating": 2
}

###
DELETE {{host}}/blog/645826948b823bac793b1a12



