@host = http://localhost:8000

###
GET {{host}}

###
GET {{host}}/blog 

###
POST {{host}}/blog 
Content-Type: application/json

{
    "author": "Mike",
    "email": "mike@gmail.com",
    "topic": "art",
    "text" : "Music day",
    "rating": 4
}

